### ISSUE TITLE
Archive & Deprecate

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/window.ipfs-is-required#4]
@lidel should we archive the repo & deprecate the module? Does not seem to be in use.

**Comment by lidel** [comment]
@hacdias yes, this should follow checklist from https://github.com/ipfs-inactive/window.ipfs-fallback/issues/3, namely:
- readme
- npm
- move to https://github.com/ipfs-inactive/

**Comment by hacdias** [comment]
@lidel just added a note to the README and deprecated the NPM module.

I don't have permissions to move to https://github.com/ipfs-inactive.

**Comment by lidel** [comment]
@hsanjuan / @daviddias are you able to help with move  of this repo to @ipfs-inactive?

**Comment by lidel** [comment]
Still needs someone to move this to @ipfs-inactive and archive it
